 language:
      - java
  services:
      - mysql
  jdk:
      - oraclejdk8
      - openjdk7
  script:
      - mvn clean test 
  cache:
      directories:
          - $HOME/.m2
  dist:
      - trusty
  sudo:
      - false
  notifications:
      - email: true